kind: ServiceAccount
apiVersion: v1
metadata:
  name: metric-adapter
  namespace: crane-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metric-adapter
  name: metric-adapter
  namespace: crane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-adapter
  template:
    metadata:
      labels:
        app: metric-adapter
    spec:
      serviceAccountName: metric-adapter
      containers:
        - name: metric-adapter
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
          image: docker.io/gocrane/metric-adapter:1df25bb
          imagePullPolicy: IfNotPresent
          args:
            - /metric-adapter
            - --secure-port=6443
            - --alsologtostderr=true
            - --remote-adapter=true
            - --remote-adapter-service-namespace=kube-system
            - --remote-adapter-service-name=hpa-metrics-service
            - --remote-adapter-service-port=443
            - --api-qps=300
            - --api-burst=400
          ports:
            - containerPort: 6443
              name: https
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
      volumes:
        - name: temp-vol
          emptyDir: {}