
apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: craned
  namespace: crane-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: craned
  namespace: crane-system
  labels:
    app: craned
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craned
  template:
    metadata:
      labels:
        app: craned
    spec:
      serviceAccountName: craned
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: craned
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
          image: docker.io/gocrane/craned:v0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /craned
            - --prometheus-address=http://kvass-thanos.kube-system:9090
            - --feature-gates=Analysis=true,TimeSeriesPrediction=true,Autoscaling=true
            - --recommendation-config-file=/tmp/recommendation-config/config_set.yaml
            - --ehpa-propagation-annotation-prefixes=platform.stke
            - --ehpa-propagation-labels=k8s-app
            - --ehpa-propagation-labels=qcloud-app
            - -v=4
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - name: config
              mountPath: /tmp/recommendation-config
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-tls
        - name: config
          configMap:
            name: recommendation-config
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo2Z0F3SUJBZ0lKQU9vSDdESmN5UkM3TUEwR0NTcUdTSWIzRFFFQkJRVUFNQkF4RGpBTUJnTlYKQkFNTUJXTnlZVzVsTUI0WERUSXlNREl4TnpBNE5EWTFORm9YRFRNeU1ESXhOVEE0TkRZMU5Gb3dLekVwTUNjRwpBMVVFQXd3Z2QyVmlhRzl2YXkxelpYSjJhV05sTG1OeVlXNWxMWE41YzNSbGJTNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURFY05vaVJQMlgrSXQzcFRHV0tHM2dNQkFneGhabk83M1kKSS9BZlpmY0tFSWQ4U1QzM0ZpbVNKTVMwWHp5QWxIVCtUeXhFa2hNZ2YzV0ZTV0Jibi9BMFFwSy9LTjV2V2lYcgpHZENpUkxEMUVEaWpJSHN1ci96NWdSLzRWU3Z0NkJpVUZQNmVPamI1TlRnUFFUN2dSUzdqSVpsTXlKWnpXMTNZClFJZ2l2ck1wM2ozUlRrdWk1TlYzUmRjSmdpU0NDazBSVlRwa1FtVUp0UzRJMm5GTEs1L0p1MmhMd3lyZHhFVzAKTkQ2dVVad3EreTl5QlZWK2dRTnR3d1R4OGtvS2ZKWnhLZDlQSHRNaHJQQitrUlgvTkRyU0pVN3lTckw4Q1dWdQpjV24xdXBXVTJsSXRkMHljOXRiTHdEbncrS2xSZ0cwUlVDYklGd1Q4Q0pKOUFQN1hLOFNUQWdNQkFBR2pnWmN3CmdaUXdDUVlEVlIwVEJBSXdBREFMQmdOVkhROEVCQU1DQmVBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUcKQ0NzR0FRVUZCd01CTUZzR0ExVWRFUVJVTUZLQ0lIZGxZbWh2YjJzdGMyVnlkbWxqWlM1amNtRnVaUzF6ZVhOMApaVzB1YzNaamdpNTNaV0pvYjI5ckxYTmxjblpwWTJVdVkzSmhibVV0YzNsemRHVnRMbk4yWXk1amJIVnpkR1Z5CkxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkJRVUFBNElCQVFDQnYzOTlvQ3B2b1VnSlFaL0c0S2NNMGY3aDZsYVUKVDBSWWZmMGMvZlFSRHM2VkVFNWt3ZjJjM3FmdU4zYXdTUDZCOVhCaHNwc0dxOWZYQ25Mc0pZTS9VNXYreGdsTgp3a1dlcjNBM0JTd3hvY2tXbVZ2Wk5SV2hZSkJMeEhsY3pOS3NabE4yRjBpUmNvSGRlb2hKbE9LdDdtQ3lhNEF2CmN5VkNnWDJKQWVJbTRKYUVSQjgrZUpzS0FTbnpRNjRFN3lVMXJCeERxZGh3bVV1Q0E5VytIV2N1WkJucXU4eU8KTWVRTG9CYUxLT0diYWk0cUtIQk9EWTEzN2JhM1dpN1Rxc1ljM1Z5aWlrS0dZTlovUzdPOGk2R0QrNnUwQXVQSQpRQ3lMdmc2VjdrU2c5UURsUjhEY09NMmwxMHRxTTZKYSttbDNnSldkNVo3UHZSa1cyTFkyTmdtbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeEhEYUlrVDlsL2lMZDZVeGxpaHQ0REFRSU1ZV1p6dTkyQ1B3SDJYM0NoQ0hmRWs5Cjl4WXBraVRFdEY4OGdKUjAvazhzUkpJVElIOTFoVWxnVzUvd05FS1N2eWplYjFvbDZ4blFva1N3OVJBNG95QjcKTHEvOCtZRWYrRlVyN2VnWWxCVCtuam8yK1RVNEQwRSs0RVV1NHlHWlRNaVdjMXRkMkVDSUlyNnpLZDQ5MFU1TApvdVRWZDBYWENZSWtnZ3BORVZVNlpFSmxDYlV1Q05weFN5dWZ5YnRvUzhNcTNjUkZ0RFErcmxHY0t2c3ZjZ1ZWCmZvRURiY01FOGZKS0NueVdjU25mVHg3VElhendmcEVWL3pRNjBpVk84a3F5L0FsbGJuRnA5YnFWbE5wU0xYZE0KblBiV3k4QTU4UGlwVVlCdEVWQW15QmNFL0FpU2ZRRCsxeXZFa3dJREFRQUJBb0lCQVFDZWowVFRNb0xMUHZnOApHOS81aHlxaE1jcGkyZUZOZElCWlRURE45enkvSi9aa1VLNHVtZm4yRjYyYXRlQ2RITGVPYWhPZVNaWWN2aVQ2CjcrNVNKcmY1UnQ4eVkyZWYwOUVWZ21IUUNNZ1pGdjNRVmpCM3o5L08rUFg0T2E5YXVlUFU2MWxXR0VFMVNFcTIKcllCMkFBSEhuZUFpaFNwRGRMVThEMktUUVFCV3dyend2L3o5VG52aXc1aGRac1NmRGJzelc1MUlHTlpRdmplOApSUC91dWZuSU9jTksvazU3dUJVU3pCK3RsUFo5TGhCT2piMDl2eHdyMlVUY2lqYkFSOW01Y0dqT0dKTEZRUjlGCnlzLytJMHdNLzJ2Z0xrYnUwanJ2aUV1aWI1MThxaGNBS2dJTkxTeXBneFF6UGxhSGIvUUhNcitTelhxMWYxZEIKdmswK0NWNVpBb0dCQU95djN2dU1IWEptRDgxL29KZVYvSWhONjhnMWRDdnlHeWxNVXRUT3pKTC9ObTQzaWZmagoybXk5d0FBb2gyMXJ3NVhERytDWkYzM2tkM0lZd0VrU0dob2FSR29oRm9YbUxuTmdmOTBnVkVWMTJPZjdlSUdjCitKb1RSM0Z6b3pZUlJyRTV5NEs5TE5nRVAyY3BVKzlON1Zsd0VZSVBwRndDcTloNys3eVJlQ3g5QW9HQkFOUjQKU0lIQ1gxVjQzVFdSVEpwY3E0WENNL1B5dlB1b2JGczVXcHZPQnZEeHM1WnExMVdSZGpOOEJwUzBTeDBsTTBSRwpPdnkzZVl6VzFJTFEvZjVFZU11Y3lCZE1NZFJPV0JoYlF0N212MFdyVEs3NS9EeXpMdmJrZ1Z3cG9XaHlPRUhtClZXWXlLTmsxSitWTzgyYnE0dWZGQVJLZHMwRUloMWYzZjZ2K0RsSlBBb0dCQU5ncHIwNnhvdHN1RjFTcE1UUUEKU1lqN0VWSGliOTBLMm4rWE16Y2tQM1lwRzc4QmZrSWxtUUVqTTAxeHRtM2FzOS85TjJLaXJ1L05Uc0dubFVXbgpBS3ZDUGFWbjNyZ2ZoMkRjU3lyYk1kdldTMmxqSTZYTWhNZkN2OGIvdzVuSG9YYU93QzBCTlFsOHA2TkIvV1JiCkdXQkxsOUhmRTA3dEthRW5hcnZIWjZmSkFvR0FLaXBNeVdPWG85QytwYmpXS1BRbkhmNXliUUZKTy9BcXdOZmIKQVh5YnFBbHZpSFJmazUyd2hYc2htelZFaXQ0dEZHbVRueitTSWI4b29XVjBZcGVZR1dCZDNUSEQyY3hLYzFyNQpKRjlLcWpyYWx3Y0paY3B4a1pHN2tseTRxWSt4Vm5LdGxBQjBWdGJUdWhBM0FiK3ZsQ3Rta1JrMno3c3ZrT2VQCk1NVFVkc1VDZ1lFQTIrZkFUelhweFZhM3NEVXVON3NQb3FFUnFnVzU3WXdtYUVWTUZJRHQyVGhkRUJ3OGFzSFoKNks5SnRyMnlOalBXMXRlVWoySVplQldSZWxwYTFkZjFzaXQzZ1VPSDFLWlk0cDB5cmNFS0xwSTRiemcvcVdvOApYMUJDRWx0UGoyMXpZMUxBY2FtLzR4VlNTRkZIUFh0ZW4zMUR0ZlBRNEFjSGVvcGpEMm5WS280PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: crane-system
type: kubernetes.io/tls

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config
  namespace: crane-system
data:
  config_set.yaml: |-
    apiVersion: analysis.crane.io/v1alpha1
    kind: ConfigSet
    configs:
      - targets: []
        properties:
          cpu-request-percentile: "0.98"
          ehpa.deployment-min-replicas: "1"
          ehpa.statefulset-min-replicas: "1"
          ehpa.workload-min-replicas: "1"
          ehpa.pod-min-ready-seconds: "30"
          ehpa.pod-available-ratio: "0.5"
